# Generated by Django 3.0.5 on 2020-04-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('memberid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('todos', models.CharField(max_length=50)),
                ('todostatus', models.IntegerField()),
                ('datecreated', models.DateTimeField(auto_now=True)),
                ('datefinished', models.DateTimeField(auto_now=True)),
                ('agreedbymom', models.IntegerField()),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytodo.Member')),
            ],
        ),
    ]
