# Generated by Django 3.0.5 on 2020-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='agreedbymom',
            field=models.IntegerField(default='0'),
        ),
    ]
